version: '3.9'

services:
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d animal-chipization"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
  tests:
    image: mrexpen/planet_olymp_phase2
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - api
    environment:
      SERVER_URL: http://api:8000
      STAGE: 2
